services:
  db:
    image: postgres:15-alpine
    container_name: world-pet-db
    restart: always
    environment:
      POSTGRES_USER: worldpetuser
      POSTGRES_PASSWORD: worldpetpassword
      POSTGRES_DB: world_pet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: world-pet-redis
    restart: always
    command: redis-server --requirepass worldpetredispassword
    ports:
      - "6379:6379"

volumes:
  postgres_data:
